import './global.css';
import { someFunction } from './someFunction';

export const metadata = {
  title: 'Welcome to test-sc',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(someFunction());

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
